# Python 连接气象自动站数据

In [3]:
import pymssql 
import pandas as pd
server = "172.21.158.201"    # 连接服务器地址
user = "down"# 连接帐号
password = "downx"# 连接密码

conn = pymssql.connect(server, user, password, "ZJSZDZDB")  #获取连接

cursor = conn.cursor() # 获取光标
cursor.execute('USE ZJSZDZDB' )
sql  = "select IIiii ,MAX(fFy*1000+dFy) AS Expr1 FROM Tab_Aws WHERE (IIiii IN('58665','58559','58568')) AND (tTime BETWEEN '2020-7-14 1:00:01' AND '2020-7-14 05:00:00') GROUP BY IIiii"

cursor.execute(sql) 
#select IIiii ,MAX(fFy*1000+dFy) AS Expr1 FROM Tab_Aws WHERE (IIiii IN('58665','58559','58568','58652')) AND (tTime BETWEEN '2020-7-14 2:00:01' AND '2020-7-14 05:00:00') GROUP BY IIiii
#sql2 = "GO"
#cursor.execute(sql2)
row = cursor.fetchall()
print(row)
print(pd.DataFrame(list(row)).shape)
#connect.commit()  # 提交
cursor.close()  # 关闭游标
conn.close()  # 关闭连接

[]
(0, 0)

# Python连接AQI数据

In [11]:
import pymssql 
import pandas as pd
server = "10.135.30.38"    # 连接服务器地址
user = "AQIuser"# 连接帐号
password = "123456"# 连接密码

conn = pymssql.connect(server, user, password, "DB_AQI")  #获取连接

cursor = conn.cursor() # 获取光标
cursor.execute('USE DB_AQI' )
sql  = "select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665'and Observtime like '20150301__')"

cursor.execute(sql) 
#select IIiii ,MAX(fFy*1000+dFy) AS Expr1 FROM Tab_Aws WHERE (IIiii IN('58665','58559','58568','58652')) AND (tTime BETWEEN '2020-7-14 2:00:01' AND '2020-7-14 05:00:00') GROUP BY IIiii
#sql2 = "GO"
#cursor.execute(sql2)
row = cursor.fetchall()
#print(row)
#print(pd.DataFrame(list(row)).shape)
#connect.commit()  # 提交
cursor.close()  # 关闭游标
conn.close()  # 关闭连接
a = list(row)
print(a[0][0])

18.254166666666666

In [9]:

date = ""
sql  = "select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665'and Observtime like '20150301__')"
def connect(sql,date):
    server = "10.135.30.38"
    user = "AQIuser"# 连接帐号
    password = "123456"# 连接密码
    conn = pymssql.connect(server, user, password, "DB_AQI")  #获取连接
    cursor = conn.cursor() # 获取光标
    cursor.execute('USE DB_AQI' )
    sql  = sql#"select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665'and Observtime like '20150301__')"
    cursor.execute(sql) 
    row = cursor.fetchall()
    cursor.close()  # 关闭游标
    conn.close()  # 关闭连接
    data  = list(row)
    ave = data[0][0]
    return ave
a=connect(sql,date)
print(a)

18.254166666666666

# 读取自动站数据，并计算逐月平均

In [26]:
month = []
for i in range(1,32):
    #print (str(i).rjust(2,'0'))
    day = str(i).rjust(2,'0')
    sql = "select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665'and Observtime like '201503" + day + "__')"
    ave = connect(sql,date)
    month.append(ave)

In [25]:
print(month)

[18.254166666666666, 51.7875, 41.94166666666666, 33.80833333333333, 23.183333333333334, 23.266666666666666, 34.47916666666666, 38.041666666666664, 24.183333333333334, 27.620833333333337, 29.19583333333333, 52.13333333333333, 43.79166666666666, 44.57500000000002, 24.712500000000002, 24.70833333333334, 28.158333333333328, 27.733333333333334, 37.88333333333333, 43.82083333333335, -84.93333333333332, 59.612500000000004, 31.162499999999998, 10.566666666666668, 12.766666666666666, 22.704166666666666, 13.654166666666669, 31.92916666666666, 47.37916666666667, 27.379166666666663, -9.050000000000006]

# 保存一年的数据

In [17]:
station = "'58665'"
year = "2015"
days = [31,28,31,30,31,30,31,31,30,31,30,31]
data = []
for i in range(1,13):
    
    print (str(i).rjust(2,'0'),i)
    month = str(i).rjust(2,'0')
    day_num = days[i-1]
    print(day_num)
    for j in range(1,day_num+1):
        print(j)
        day = str(j).rjust(2,'0')
        sql = "select avg(Pm2_5) from RealTimeData_"+year+month+" "+"where(Stationnum = "+station+" "+"and Observtime like"+" "+"'"+year+month + day + "__')"
        print(sql)
        ave = connect(sql,date)
        data.append(ave)

01 1
31
1
select avg(Pm2_5) from RealTimeData_201501 where(Stationnum = '58665' and Observtime like '20150101__')
2
select avg(Pm2_5) from RealTimeData_201501 where(Stationnum = '58665' and Observtime like '20150102__')
3
select avg(Pm2_5) from RealTimeData_201501 where(Stationnum = '58665' and Observtime like '20150103__')
4
select avg(Pm2_5) from RealTimeData_201501 where(Stationnum = '58665' and Observtime like '20150104__')
5
select avg(Pm2_5) from RealTimeData_201501 where(Stationnum = '58665' and Observtime like '20150105__')
6
select avg(Pm2_5) from RealTimeData_201501 where(Stationnum = '58665' and Observtime like '20150106__')
7
select avg(Pm2_5) from RealTimeData_201501 where(Stationnum = '58665' and Observtime like '20150107__')
8
select avg(Pm2_5) from RealTimeData_201501 where(Stationnum = '58665' and Observtime like '20150108__')
9
select avg(Pm2_5) from RealTimeData_201501 where(Stationnum = '58665' and Observtime like '20150109__')
10
select avg(Pm2_5) from RealTimeData_201501 where(Stationnum = '58665' and Observtime like '20150110__')
11
select avg(Pm2_5) from RealTimeData_201501 where(Stationnum = '58665' and Observtime like '20150111__')
12
select avg(Pm2_5) from RealTimeData_201501 where(Stationnum = '58665' and Observtime like '20150112__')
13
select avg(Pm2_5) from RealTimeData_201501 where(Stationnum = '58665' and Observtime like '20150113__')
14
select avg(Pm2_5) from RealTimeData_201501 where(Stationnum = '58665' and Observtime like '20150114__')
15
select avg(Pm2_5) from RealTimeData_201501 where(Stationnum = '58665' and Observtime like '20150115__')
16
select avg(Pm2_5) from RealTimeData_201501 where(Stationnum = '58665' and Observtime like '20150116__')
17
select avg(Pm2_5) from RealTimeData_201501 where(Stationnum = '58665' and Observtime like '20150117__')
18
select avg(Pm2_5) from RealTimeData_201501 where(Stationnum = '58665' and Observtime like '20150118__')
19
select avg(Pm2_5) from RealTimeData_201501 where(Stationnum = '58665' and Observtime like '20150119__')
20
select avg(Pm2_5) from RealTimeData_201501 where(Stationnum = '58665' and Observtime like '20150120__')
21
select avg(Pm2_5) from RealTimeData_201501 where(Stationnum = '58665' and Observtime like '20150121__')
22
select avg(Pm2_5) from RealTimeData_201501 where(Stationnum = '58665' and Observtime like '20150122__')
23
select avg(Pm2_5) from RealTimeData_201501 where(Stationnum = '58665' and Observtime like '20150123__')
24
select avg(Pm2_5) from RealTimeData_201501 where(Stationnum = '58665' and Observtime like '20150124__')
25
select avg(Pm2_5) from RealTimeData_201501 where(Stationnum = '58665' and Observtime like '20150125__')
26
select avg(Pm2_5) from RealTimeData_201501 where(Stationnum = '58665' and Observtime like '20150126__')
27
select avg(Pm2_5) from RealTimeData_201501 where(Stationnum = '58665' and Observtime like '20150127__')
28
select avg(Pm2_5) from RealTimeData_201501 where(Stationnum = '58665' and Observtime like '20150128__')
29
select avg(Pm2_5) from RealTimeData_201501 where(Stationnum = '58665' and Observtime like '20150129__')
30
select avg(Pm2_5) from RealTimeData_201501 where(Stationnum = '58665' and Observtime like '20150130__')
31
select avg(Pm2_5) from RealTimeData_201501 where(Stationnum = '58665' and Observtime like '20150131__')
02 2
28
1
select avg(Pm2_5) from RealTimeData_201502 where(Stationnum = '58665' and Observtime like '20150201__')
2
select avg(Pm2_5) from RealTimeData_201502 where(Stationnum = '58665' and Observtime like '20150202__')
3
select avg(Pm2_5) from RealTimeData_201502 where(Stationnum = '58665' and Observtime like '20150203__')
4
select avg(Pm2_5) from RealTimeData_201502 where(Stationnum = '58665' and Observtime like '20150204__')
5
select avg(Pm2_5) from RealTimeData_201502 where(Stationnum = '58665' and Observtime like '20150205__')
6
select avg(Pm2_5) from RealTimeData_201502 where(Stationnum = '58665' and Observtime like '20150206__')
7
select avg(Pm2_5) from RealTimeData_201502 where(Stationnum = '58665' and Observtime like '20150207__')
8
select avg(Pm2_5) from RealTimeData_201502 where(Stationnum = '58665' and Observtime like '20150208__')
9
select avg(Pm2_5) from RealTimeData_201502 where(Stationnum = '58665' and Observtime like '20150209__')
10
select avg(Pm2_5) from RealTimeData_201502 where(Stationnum = '58665' and Observtime like '20150210__')
11
select avg(Pm2_5) from RealTimeData_201502 where(Stationnum = '58665' and Observtime like '20150211__')
12
select avg(Pm2_5) from RealTimeData_201502 where(Stationnum = '58665' and Observtime like '20150212__')
13
select avg(Pm2_5) from RealTimeData_201502 where(Stationnum = '58665' and Observtime like '20150213__')
14
select avg(Pm2_5) from RealTimeData_201502 where(Stationnum = '58665' and Observtime like '20150214__')
15
select avg(Pm2_5) from RealTimeData_201502 where(Stationnum = '58665' and Observtime like '20150215__')
16
select avg(Pm2_5) from RealTimeData_201502 where(Stationnum = '58665' and Observtime like '20150216__')
17
select avg(Pm2_5) from RealTimeData_201502 where(Stationnum = '58665' and Observtime like '20150217__')
18
select avg(Pm2_5) from RealTimeData_201502 where(Stationnum = '58665' and Observtime like '20150218__')
19
select avg(Pm2_5) from RealTimeData_201502 where(Stationnum = '58665' and Observtime like '20150219__')
20
select avg(Pm2_5) from RealTimeData_201502 where(Stationnum = '58665' and Observtime like '20150220__')
21
select avg(Pm2_5) from RealTimeData_201502 where(Stationnum = '58665' and Observtime like '20150221__')
22
select avg(Pm2_5) from RealTimeData_201502 where(Stationnum = '58665' and Observtime like '20150222__')
23
select avg(Pm2_5) from RealTimeData_201502 where(Stationnum = '58665' and Observtime like '20150223__')
24
select avg(Pm2_5) from RealTimeData_201502 where(Stationnum = '58665' and Observtime like '20150224__')
25
select avg(Pm2_5) from RealTimeData_201502 where(Stationnum = '58665' and Observtime like '20150225__')
26
select avg(Pm2_5) from RealTimeData_201502 where(Stationnum = '58665' and Observtime like '20150226__')
27
select avg(Pm2_5) from RealTimeData_201502 where(Stationnum = '58665' and Observtime like '20150227__')
28
select avg(Pm2_5) from RealTimeData_201502 where(Stationnum = '58665' and Observtime like '20150228__')
03 3
31
1
select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665' and Observtime like '20150301__')
2
select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665' and Observtime like '20150302__')
3
select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665' and Observtime like '20150303__')
4
select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665' and Observtime like '20150304__')
5
select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665' and Observtime like '20150305__')
6
select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665' and Observtime like '20150306__')
7
select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665' and Observtime like '20150307__')
8
select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665' and Observtime like '20150308__')
9
select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665' and Observtime like '20150309__')
10
select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665' and Observtime like '20150310__')
11
select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665' and Observtime like '20150311__')
12
select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665' and Observtime like '20150312__')
13
select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665' and Observtime like '20150313__')
14
select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665' and Observtime like '20150314__')
15
select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665' and Observtime like '20150315__')
16
select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665' and Observtime like '20150316__')
17
select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665' and Observtime like '20150317__')
18
select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665' and Observtime like '20150318__')
19
select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665' and Observtime like '20150319__')
20
select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665' and Observtime like '20150320__')
21
select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665' and Observtime like '20150321__')
22
select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665' and Observtime like '20150322__')
23
select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665' and Observtime like '20150323__')
24
select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665' and Observtime like '20150324__')
25
select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665' and Observtime like '20150325__')
26
select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665' and Observtime like '20150326__')
27
select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665' and Observtime like '20150327__')
28
select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665' and Observtime like '20150328__')
29
select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665' and Observtime like '20150329__')
30
select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665' and Observtime like '20150330__')
31
select avg(Pm2_5) from RealTimeData_201503 where(Stationnum = '58665' and Observtime like '20150331__')
04 4
30
1
select avg(Pm2_5) from RealTimeData_201504 where(Stationnum = '58665' and Observtime like '20150401__')
2
select avg(Pm2_5) from RealTimeData_201504 where(Stationnum = '58665' and Observtime like '20150402__')
3
select avg(Pm2_5) from RealTimeData_201504 where(Stationnum = '58665' and Observtime like '20150403__')
4
select avg(Pm2_5) from RealTimeData_201504 where(Stationnum = '58665' and Observtime like '20150404__')
5
select avg(Pm2_5) from RealTimeData_201504 where(Stationnum = '58665' and Observtime like '20150405__')
6
select avg(Pm2_5) from RealTimeData_201504 where(Stationnum = '58665' and Observtime like '20150406__')
7
select avg(Pm2_5) from RealTimeData_201504 where(Stationnum = '58665' and Observtime like '20150407__')
8
select avg(Pm2_5) from RealTimeData_201504 where(Stationnum = '58665' and Observtime like '20150408__')
9
select avg(Pm2_5) from RealTimeData_201504 where(Stationnum = '58665' and Observtime like '20150409__')
10
select avg(Pm2_5) from RealTimeData_201504 where(Stationnum = '58665' and Observtime like '20150410__')
11
select avg(Pm2_5) from RealTimeData_201504 where(Stationnum = '58665' and Observtime like '20150411__')
12
select avg(Pm2_5) from RealTimeData_201504 where(Stationnum = '58665' and Observtime like '20150412__')
13
select avg(Pm2_5) from RealTimeData_201504 where(Stationnum = '58665' and Observtime like '20150413__')
14
select avg(Pm2_5) from RealTimeData_201504 where(Stationnum = '58665' and Observtime like '20150414__')
15
select avg(Pm2_5) from RealTimeData_201504 where(Stationnum = '58665' and Observtime like '20150415__')
16
select avg(Pm2_5) from RealTimeData_201504 where(Stationnum = '58665' and Observtime like '20150416__')
17
select avg(Pm2_5) from RealTimeData_201504 where(Stationnum = '58665' and Observtime like '20150417__')
18
select avg(Pm2_5) from RealTimeData_201504 where(Stationnum = '58665' and Observtime like '20150418__')
19
select avg(Pm2_5) from RealTimeData_201504 where(Stationnum = '58665' and Observtime like '20150419__')
20
select avg(Pm2_5) from RealTimeData_201504 where(Stationnum = '58665' and Observtime like '20150420__')
21
select avg(Pm2_5) from RealTimeData_201504 where(Stationnum = '58665' and Observtime like '20150421__')
22
select avg(Pm2_5) from RealTimeData_201504 where(Stationnum = '58665' and Observtime like '20150422__')
23
select avg(Pm2_5) from RealTimeData_201504 where(Stationnum = '58665' and Observtime like '20150423__')
24
select avg(Pm2_5) from RealTimeData_201504 where(Stationnum = '58665' and Observtime like '20150424__')
25
select avg(Pm2_5) from RealTimeData_201504 where(Stationnum = '58665' and Observtime like '20150425__')
26
select avg(Pm2_5) from RealTimeData_201504 where(Stationnum = '58665' and Observtime like '20150426__')
27
select avg(Pm2_5) from RealTimeData_201504 where(Stationnum = '58665' and Observtime like '20150427__')
28
select avg(Pm2_5) from RealTimeData_201504 where(Stationnum = '58665' and Observtime like '20150428__')
29
select avg(Pm2_5) from RealTimeData_201504 where(Stationnum = '58665' and Observtime like '20150429__')
30
select avg(Pm2_5) from RealTimeData_201504 where(Stationnum = '58665' and Observtime like '20150430__')
05 5
31
1
select avg(Pm2_5) from RealTimeData_201505 where(Stationnum = '58665' and Observtime like '20150501__')
2
select avg(Pm2_5) from RealTimeData_201505 where(Stationnum = '58665' and Observtime like '20150502__')
3
select avg(Pm2_5) from RealTimeData_201505 where(Stationnum = '58665' and Observtime like '20150503__')
4
select avg(Pm2_5) from RealTimeData_201505 where(Stationnum = '58665' and Observtime like '20150504__')
5
select avg(Pm2_5) from RealTimeData_201505 where(Stationnum = '58665' and Observtime like '20150505__')
6
select avg(Pm2_5) from RealTimeData_201505 where(Stationnum = '58665' and Observtime like '20150506__')
7
select avg(Pm2_5) from RealTimeData_201505 where(Stationnum = '58665' and Observtime like '20150507__')
8
select avg(Pm2_5) from RealTimeData_201505 where(Stationnum = '58665' and Observtime like '20150508__')
9
select avg(Pm2_5) from RealTimeData_201505 where(Stationnum = '58665' and Observtime like '20150509__')
10
select avg(Pm2_5) from RealTimeData_201505 where(Stationnum = '58665' and Observtime like '20150510__')
11
select avg(Pm2_5) from RealTimeData_201505 where(Stationnum = '58665' and Observtime like '20150511__')
12
select avg(Pm2_5) from RealTimeData_201505 where(Stationnum = '58665' and Observtime like '20150512__')
13
select avg(Pm2_5) from RealTimeData_201505 where(Stationnum = '58665' and Observtime like '20150513__')
14
select avg(Pm2_5) from RealTimeData_201505 where(Stationnum = '58665' and Observtime like '20150514__')
15
select avg(Pm2_5) from RealTimeData_201505 where(Stationnum = '58665' and Observtime like '20150515__')
16
select avg(Pm2_5) from RealTimeData_201505 where(Stationnum = '58665' and Observtime like '20150516__')
17
select avg(Pm2_5) from RealTimeData_201505 where(Stationnum = '58665' and Observtime like '20150517__')
18
select avg(Pm2_5) from RealTimeData_201505 where(Stationnum = '58665' and Observtime like '20150518__')
19
select avg(Pm2_5) from RealTimeData_201505 where(Stationnum = '58665' and Observtime like '20150519__')
20
select avg(Pm2_5) from RealTimeData_201505 where(Stationnum = '58665' and Observtime like '20150520__')
21
select avg(Pm2_5) from RealTimeData_201505 where(Stationnum = '58665' and Observtime like '20150521__')
22
select avg(Pm2_5) from RealTimeData_201505 where(Stationnum = '58665' and Observtime like '20150522__')
23
select avg(Pm2_5) from RealTimeData_201505 where(Stationnum = '58665' and Observtime like '20150523__')
24
select avg(Pm2_5) from RealTimeData_201505 where(Stationnum = '58665' and Observtime like '20150524__')
25
select avg(Pm2_5) from RealTimeData_201505 where(Stationnum = '58665' and Observtime like '20150525__')
26
select avg(Pm2_5) from RealTimeData_201505 where(Stationnum = '58665' and Observtime like '20150526__')
27
select avg(Pm2_5) from RealTimeData_201505 where(Stationnum = '58665' and Observtime like '20150527__')
28
select avg(Pm2_5) from RealTimeData_201505 where(Stationnum = '58665' and Observtime like '20150528__')
29
select avg(Pm2_5) from RealTimeData_201505 where(Stationnum = '58665' and Observtime like '20150529__')
30
select avg(Pm2_5) from RealTimeData_201505 where(Stationnum = '58665' and Observtime like '20150530__')
31
select avg(Pm2_5) from RealTimeData_201505 where(Stationnum = '58665' and Observtime like '20150531__')
06 6
30
1
select avg(Pm2_5) from RealTimeData_201506 where(Stationnum = '58665' and Observtime like '20150601__')
2
select avg(Pm2_5) from RealTimeData_201506 where(Stationnum = '58665' and Observtime like '20150602__')
3
select avg(Pm2_5) from RealTimeData_201506 where(Stationnum = '58665' and Observtime like '20150603__')
4
select avg(Pm2_5) from RealTimeData_201506 where(Stationnum = '58665' and Observtime like '20150604__')
5
select avg(Pm2_5) from RealTimeData_201506 where(Stationnum = '58665' and Observtime like '20150605__')
6
select avg(Pm2_5) from RealTimeData_201506 where(Stationnum = '58665' and Observtime like '20150606__')
7
select avg(Pm2_5) from RealTimeData_201506 where(Stationnum = '58665' and Observtime like '20150607__')
8
select avg(Pm2_5) from RealTimeData_201506 where(Stationnum = '58665' and Observtime like '20150608__')
9
select avg(Pm2_5) from RealTimeData_201506 where(Stationnum = '58665' and Observtime like '20150609__')
10
select avg(Pm2_5) from RealTimeData_201506 where(Stationnum = '58665' and Observtime like '20150610__')
11
select avg(Pm2_5) from RealTimeData_201506 where(Stationnum = '58665' and Observtime like '20150611__')
12
select avg(Pm2_5) from RealTimeData_201506 where(Stationnum = '58665' and Observtime like '20150612__')
13
select avg(Pm2_5) from RealTimeData_201506 where(Stationnum = '58665' and Observtime like '20150613__')
14
select avg(Pm2_5) from RealTimeData_201506 where(Stationnum = '58665' and Observtime like '20150614__')
15
select avg(Pm2_5) from RealTimeData_201506 where(Stationnum = '58665' and Observtime like '20150615__')
16
select avg(Pm2_5) from RealTimeData_201506 where(Stationnum = '58665' and Observtime like '20150616__')
17
select avg(Pm2_5) from RealTimeData_201506 where(Stationnum = '58665' and Observtime like '20150617__')
18
select avg(Pm2_5) from RealTimeData_201506 where(Stationnum = '58665' and Observtime like '20150618__')
19
select avg(Pm2_5) from RealTimeData_201506 where(Stationnum = '58665' and Observtime like '20150619__')
20
select avg(Pm2_5) from RealTimeData_201506 where(Stationnum = '58665' and Observtime like '20150620__')
21
select avg(Pm2_5) from RealTimeData_201506 where(Stationnum = '58665' and Observtime like '20150621__')
22
select avg(Pm2_5) from RealTimeData_201506 where(Stationnum = '58665' and Observtime like '20150622__')
23
select avg(Pm2_5) from RealTimeData_201506 where(Stationnum = '58665' and Observtime like '20150623__')
24
select avg(Pm2_5) from RealTimeData_201506 where(Stationnum = '58665' and Observtime like '20150624__')
25
select avg(Pm2_5) from RealTimeData_201506 where(Stationnum = '58665' and Observtime like '20150625__')
26
select avg(Pm2_5) from RealTimeData_201506 where(Stationnum = '58665' and Observtime like '20150626__')
27
select avg(Pm2_5) from RealTimeData_201506 where(Stationnum = '58665' and Observtime like '20150627__')
28
select avg(Pm2_5) from RealTimeData_201506 where(Stationnum = '58665' and Observtime like '20150628__')
29
select avg(Pm2_5) from RealTimeData_201506 where(Stationnum = '58665' and Observtime like '20150629__')
30
select avg(Pm2_5) from RealTimeData_201506 where(Stationnum = '58665' and Observtime like '20150630__')
07 7
31
1
select avg(Pm2_5) from RealTimeData_201507 where(Stationnum = '58665' and Observtime like '20150701__')
2
select avg(Pm2_5) from RealTimeData_201507 where(Stationnum = '58665' and Observtime like '20150702__')
3
select avg(Pm2_5) from RealTimeData_201507 where(Stationnum = '58665' and Observtime like '20150703__')
4
select avg(Pm2_5) from RealTimeData_201507 where(Stationnum = '58665' and Observtime like '20150704__')
5
select avg(Pm2_5) from RealTimeData_201507 where(Stationnum = '58665' and Observtime like '20150705__')
6

In [18]:
print(data)

[42.975, 53.17916666666667, 58.37083333333334, 68.88333333333334, 78.07916666666665, 86.6875, 39.07083333333333, 82.96666666666665, 99.51249999999999, 118.3, 82.12500000000001, 51.94583333333332, 14.716666666666667, 10.433333333333334, 38.30833333333334, 54.31666666666667, 103.09166666666668, 89.78333333333332, 79.25416666666666, 61.0875, 60.808333333333316, 88.24583333333334, 117.1125, 84.27916666666665, 77.47916666666667, 104.37916666666666, 45.604166666666664, 20.787499999999998, 33.604166666666664, 28.304166666666674, 62.1625, 33.19583333333333, 45.45833333333332, 33.566666666666656, 47.85416666666666, 73.07083333333334, 54.59166666666667, 65.43333333333332, 62.337499999999984, 27.400000000000002, 47.745833333333344, 65.96666666666668, 65.075, 92.425, 72.65, 66.72916666666667, 63.98750000000001, 78.59166666666665, 78.29583333333333, 44.995833333333316, 32.75833333333332, 37.96666666666667, 43.270833333333336, 35.833333333333336, 24.037500000000005, 26.64583333333334, 16.6125, 15.995833333333332, 9.408333333333333, 18.254166666666666, 51.7875, 41.94166666666666, 33.80833333333333, 23.183333333333334, 23.266666666666666, 34.47916666666666, 38.041666666666664, 24.183333333333334, 27.620833333333337, 29.19583333333333, 52.13333333333333, 43.79166666666666, 44.57500000000002, 24.712500000000002, 24.70833333333334, 28.158333333333328, 27.733333333333334, 37.88333333333333, 43.82083333333335, -84.93333333333332, 59.612500000000004, 31.162499999999998, 10.566666666666668, 12.766666666666666, 22.704166666666666, 13.654166666666669, 31.92916666666666, 47.37916666666667, 27.379166666666663, -9.050000000000006, 36.96666666666666, 18.45, 32.3125, 26.508333333333336, 96.94583333333333, 34.2, None, -341.81818181818176, 35.90416666666667, 43.1, 53.0, 49.49583333333334, 30.908333333333328, 33.729166666666664, 44.041666666666664, 55.98333333333334, 72.62499999999999, 61.35833333333333, 88.15416666666665, 42.03750000000001, 46.191666666666684, 42.7125, 52.38750000000001, 74.80416666666666, 53.45833333333332, 63.849999999999994, 72.47916666666666, 58.775000000000006, 74.05833333333332, 54.145833333333336, 59.27916666666667, 44.72083333333333, 44.75833333333333, 62.32916666666666, 35.44166666666666, 43.62083333333334, 46.87083333333333, 43.479166666666664, 35.52916666666667, 32.59166666666667, 34.60833333333333, 17.299999999999997, 26.958333333333332, 50.24166666666667, 48.67499999999999, 22.03333333333333, 27.650000000000002, 31.783333333333342, 23.70833333333334, 33.23333333333334, 16.991666666666667, 24.2375, 42.95416666666666, 38.29166666666667, 32.09583333333334, 45.587500000000006, 38.39166666666667, 48.41249999999999, 34.32083333333333, 44.35416666666666, 27.104166666666668, 31.962499999999988, 32.51666666666667, 34.22916666666667, 21.433333333333337, 47.93749999999999, 58.958333333333314, 39.25833333333333, 67.14999999999999, 38.9125, 41.487500000000004, 36.266666666666666, 32.879166666666656, 39.291666666666664, 34.42083333333334, 41.46249999999999, 36.870833333333344, 40.34583333333333, 28.412499999999998, 21.370833333333334, 16.808333333333334, 22.77916666666667, 33.295833333333334, 39.083333333333336, 19.995833333333334, 24.8875, 26.233333333333334, 30.700000000000003, 34.179166666666674, -6.4624999999999995, 49.804166666666674, 28.129166666666666, 16.241666666666667, 17.929166666666664, 25.508333333333336, 8.3375, 5.937499999999999, 10.437499999999998, 17.874999999999996, 14.083333333333334, 7.400000000000001, -81.94166666666668, 17.241666666666667, -42.93749999999999, -1.9791666666666643, 46.854166666666664, 32.170833333333334, 27.50833333333334, 32.45833333333332, 42.4375, 31.266666666666676, 15.737499999999997, 17.145833333333332, 22.075, 23.079166666666666, 30.625, 42.85, 49.31666666666667, 45.24999999999999, 36.55416666666667, 30.124999999999996, 41.60833333333333, 40.49166666666667, 32.29166666666666, 29.495833333333334, 37.662499999999994, 37.141666666666666, 31.34583333333333, 18.600000000000005, 18.7, 20.220833333333328, 25.69583333333333, 26.991666666666664, 33.28333333333334, 35.420833333333334, 38.987500000000004, 39.583333333333336, 37.22083333333334, 33.82916666666667, 44.81666666666666, 28.608333333333338, 32.074999999999996, 25.75, 22.908333333333328, 10.733333333333333, 10.0125, 23.19583333333333, 47.854166666666664, 32.97083333333334, 43.95833333333334, 34.391666666666666, 43.39166666666666, 44.0375, 50.8375, 43.179166666666674, 64.19166666666668, 68.3, 33.05833333333334, 39.32916666666667, 44.51250000000001, 29.6125, 27.629166666666666, 34.8, 54.79583333333332, 60.47916666666666, 38.291666666666664, 33.108333333333334, 19.92083333333333, 25.345833333333328, 43.39166666666667, 51.40833333333335, 58.48333333333334, 42.175, 32.3625, 36.25416666666666, 40.24583333333333, 38.449999999999996, 41.72083333333334, 33.266666666666666, 30.974999999999998, 26.166666666666668, 21.22083333333333, 26.27083333333334, 22.104166666666668, 39.191666666666656, 41.81666666666667, 24.808333333333334, 27.4875, 22.708333333333332, 29.7, 17.38333333333333, 31.504166666666663, 58.67499999999999, 53.42916666666667, 74.81666666666666, 83.23333333333333, 79.59166666666665, 51.262499999999996, 41.17083333333333, 39.9625, 35.966666666666676, 36.91249999999999, 29.450000000000003, 28.3, 43.21666666666667, 52.550000000000004, 45.63750000000001, 42.091666666666676, 50.30416666666667, 42.88333333333335, 73.24166666666666, 73.3, 18.374999999999996, 16.358333333333334, 20.05416666666667, 47.695833333333326, 62.99166666666665, 44.85833333333334, 41.45833333333333, 41.7125, 25.94583333333333, 30.891666666666666, 18.216666666666665, 39.76666666666666, 46.6, 47.74583333333333, 21.275000000000002, 32.375, 53.65833333333334, 65.58749999999999, 45.92499999999999, 19.270833333333332, 40.408333333333324, 50.008333333333326, 45.0, 31.079166666666666, 25.858333333333334, 17.979166666666668, 14.458333333333334, 18.395833333333336, 41.77916666666666, 74.23333333333333, 40.61666666666667, 30.624999999999996, 54.23333333333334, 40.37916666666667, 46.98333333333334, 37.137499999999996, 29.045833333333334, 14.712500000000004, 43.654166666666676, 40.12916666666666, 43.258333333333326, 27.504166666666666, 34.74166666666667, 70.37083333333332, 58.48333333333333, 34.37916666666666, 97.97916666666664, 71.31250000000001, 29.616666666666664, 48.38333333333333, 45.39166666666667, 39.29166666666666, 54.28333333333333, 56.791666666666664, 45.099999999999994, 40.237500000000004, 36.291666666666664, 53.04615384615385, -130.43529411764706, 44.275000000000006, 59.76666666666667, 60.35, 88.75]

In [19]:
print(len(data))

365